#!/bin/bash
#set -x

source ../common.sh

title "Test python %code ordering test"

B=YYParser

function clean {
    rm -f tmp experr expout stdout stderr input *.py *.pyc
}

function createexpout() {
cat > ./expout <<EOF
pass # %code imports
pass # %code top
pass # %code requires
pass # %code provides
  pass # %code 1
  pass # %code 2
pass # %code epilogue
EOF
}

function testcase {
    tc=0
    c=0
    FAILED=""
    clean
    rm -f $B.py
    bison $SK -o $B.py $B.y
    createexpout
    # Collect the %code items in the .py file
    grep '^[ ]*pass # %code' YYParser.py >stdout
    if ! diff expout stdout ; then FAILED=1; fi
    if test "$FAILED" == 1 ; then
      echo "***Fail"
    fi
}

function testall() {
testcase
}

run
