#!/bin/bash
#set -x

source ../common.sh

title "Test python parser class and package names"

B=PrefixParser

function clean {
    rm -f tmp experr expout stdout stderr input *.py *.pyc
}

function testcase {
    FAILED=""
    clean
    rm -f $B.py
    bison $SK -o $B.py $B.y
    # look for markers in the .py file
    count=`grep -c '^class PrefixParser' $B.py`
    if test "x$count" != 'x1' ; then
      echo "***Fail: $1"
      FAILED=1
    fi
}

function testall() {
testcase
}

run
