#!/bin/bash
#set -x

source ../common.sh

title "Test parser class inheritance"

B=YYParser

function clean {
    rm -f tmp experr expout stdout stderr input *.py *.pyc
}

function testcase {
    totalcount=0
    count=0
    FAILED=""
    clean
    rm -f $B.py
    bison $SK -o $B.py $B.y
    # look for markers in the .py file
    count=`grep -c '^  def __init__[ ]*(self,[ ]*yylexer,[ ]*parseparam1[ ]*)' $B.py`
    totalcount=`expr $totalcount + $count`
    count=`grep -c '^    self.parseparam1 = parseparam1[ ]*$' $B.py`
    totalcount=`expr $totalcount + $count`
    if test "x$totalcount" != 'x2' ; then
      echo "***Fail: $1"
      FAILED=1
    fi
}

function testall() {
testcase
}

run
