#!/bin/bash
#set -x

source ../common.sh

title "Test yython value type enforcement"

B=YYParser

function clean {
    rm -f tmp experr expout stdout stderr input *.py *.pyc
}

function testcase {
    tc=0
    c=0
    FAILED=""
    clean
    rm -f $B.py
    bison $SK -o $B.py $B.y >./stdout 2>./stderr
    # look for markers in the .py file
    c=`grep -c 'warning: type clash on default action: <object> != <File>' ./stderr`
    tc=`expr $tc + $c` 
    if test "$tc" != 1 ; then
      echo "***Fail: $1"
      FAILED=1
    fi
}

function testall() {
testcase
}

run
